### ISSUE TITLE
Gather interface

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaComms.jl#11]
This doesn't need to be too performant, but it is helpful for debugging.

Need to think this through, but the easiest option is probably something like
```
ClimaComms.gather(ctx, array, pid=1)
```
where it concatenates along the last dimensions of the array (and assumes all other dimensions are the same)

In MPI speak, this would be something like
```
lengths = MPI.Gather(size(array)[end], comm, pid-1) # or we might be able to get this from the context?
if pid == 1
   sizeout = (size(array)[1:end-1], sum(lengths))
   arrayout = zeros(sizeout)
end
MPI.Gatherv!(arrayout, array, prod(size(array)[1:end-1]) .* lengths, pid-1)
```

**Comment by sriharshakandala** [comment]
Addressed by PR https://github.com/CliMA/ClimaComms.jl/pull/12
