### ISSUE TITLE
Specify CPU threading via device

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaComms.jl#49]
Now that we specify a device as part of the comms context, it might make sense to use this to specify threading (rather than what we do at the moment, which is invalidate a bunch of methods in ClimaCore).

So instead of `CPUDevice()`, we would have both `CPUDeviceThreading()` and `CPUDeviceNoThreading()`.

Thoughts @charleskawczynski @sriharshakandala ?

**Comment by sriharshakandala** [comment]
Can we just do `CPUDevice()` and specify the number of threads, with a default of `1`?

**Comment by simonbyrne** [comment]
I don't think we can control the exact number of threads used within a function: basically the distinction is whether we use an ordinary `for` loop, or [`Threads.@threads for`](https://docs.julialang.org/en/v1/base/multi-threading/#Base.Threads.@threads).

We could just make it a boolean flag, maybe that would be easier?

**Comment by sriharshakandala** [comment]
> I don't think we can control the exact number of threads used within a function: basically the distinction is whether we use an ordinary `for` loop, or [`Threads.@threads for`](https://docs.julialang.org/en/v1/base/multi-threading/#Base.Threads.@threads).
> 
> We could just make it a boolean flag, maybe that would be easier?

Sure. But can we not just use `Threads.@threads for` everywhere for CPU code? We just need to set `nthreads = 1` for unthreaded code! I do not see why we need to toggle between a `for` and a `threaded for`!

**Comment by sriharshakandala** [comment]
For threaded runs, we can use `max_CPU_threads` and use fewer when we do not need as many!

**Comment by simonbyrne** [comment]
Two main reasons:
- `@threads` still has overhead
- it is useful to be able to switch to serial for debugging.

**Comment by charleskawczynski** [comment]
I like the idea of using the context-- it's certainly better than the current configuration.

For the loop, I think we can write a simple macro, and dispatch between an unthreaded and threaded loop based on `CPUDeviceThreading` and `CPUDeviceNoThreading`

**Comment by charleskawczynski** [comment]
Can we still throw a more informative error in dss?

**Comment by simonbyrne** [comment]
what is `CPUDeviceSingleThreading`?

**Comment by charleskawczynski** [comment]
> what is `CPUDeviceSingleThreading`?

Brain fart, it's `CPUDeviceThreading` with 1 thread.

**Comment by simonbyrne** [comment]
We can't control the number of threads used from within julia (you can control it from outside by `--threads=1`)

**Comment by simonbyrne** [comment]
I think the simplest option for now might be to add a `CPUSingleThreadDevice`

**Comment by charleskawczynski** [comment]
Looking back at this, I think I actually meant that we could distinguish between `--threads 1` and not specifying the `--threads` keyword argument. Which I guess is only useful to compare the difference in overhead of using `Threads.@threads` or not.

**Comment by sriharshakandala** [comment]
So, is the consensus to use `CPUSinglethreadedDevice` and `CPUMultithreadedDevice` ? 
Is it ok to drop the `Device` suffix for CPUs and use `CPUSinglethreaded` and `CPUMultithreaded` ?

**Comment by simonbyrne** [comment]
Sure, but lets use CamelCase: `CPUMultiThreaded` and `CPUSingleThreaded`

**Comment by sriharshakandala** [comment]
How do we plan to extend 
```
"""
    ClimaComms.device(object)

Return the appropriate device for the specified object.
"""
device(::Array) = CPUDevice()
device(::CUDA_jl.CuArray) = CUDADevice()
device(arr::SubArray) = device(parent(arr))
```
