### ISSUE TITLE
SharedArrays backend isn't working

### ISSUE THREAD

**Issue by kpamnany** [CliMA/ClimaComms.jl#6]
On the 4th or so iteration onwards, the data sent (copied from `input`) from any of the processes is wrong/offset in some way. Seems like a synchronization problem, but the barrier seems to be working correctly? Also, on some subsequent iterations, the data sent is suddenly correct again, only to go wrong again on following iterations...

**Comment by simonbyrne** [comment]
https://github.com/JuliaConcurrent/SyncBarriers.jl might be helpful

**Comment by Sbozzolo** [comment]
Closing as no longer applicable
