### ISSUE TITLE
ClimaComms.@elapsed not working correctly on CUDADevice

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaComms.jl#82]
Unfortunately, it looks like that `ClimaComms.@elapsed` is not using `CUDA.@elapsed`. See, for example, https://buildkite.com/clima/climaatmos-ci/builds/19101#018fea6e-9626-4c61-a653-3d72a751a817

```
[ Info: sypd: 1.2842464690834364e7
[ Info: wall_time_per_timestep: 22 nanoseconds
```

**Comment by charleskawczynski** [comment]
Closed by #83
